M48
; DRILL file KiCad 10.0.3 date 2026-07-02T18:43:42
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-02T18:43:42+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0118
%
G90
G05
T1
X4.579Y-5.397
X4.712Y-5.375
X5.573Y-5.513
T2
X5.7437Y-5.25
M30
